insert into user_details(id, name, birth_date)values(1001, 'Paran', current_date);
insert into user_details(id, name, birth_date)values(1002, 'Curzon', current_date);
insert into user_details(id, name, birth_date)values(1003, 'Shamim', current_date);
insert into user_details(id, name, birth_date)values(1004, 'Baybars', current_date);
insert into post (id,description, user_id)values (1,'Test Post 1', 1001);
insert into post (id,description, user_id)values (2,'Test Post 2', 1001);
insert into post (id,description, user_id)values (3,'Test Post 3', 1002);
insert into post (id,description, user_id)values (4,'Test Post 4', 1002);
insert into post (id,description, user_id)values (5,'Test Post 5', 1003);
insert into post (id,description, user_id)values (6,'Test Post 6', 1003);